Repository PennLINC/CuBIDS, pull requests merged in 2025-02, with the labels that each got.

#419 Split out non-class methods into utils module
  cubids/cubids.py
  cubids/tests/test_cubids.py
  cubids/utils.py
Labels: refactor

#392 Use BIDS schema in CuBIDS
  cubids/cli.py
  cubids/config.py
  cubids/cubids.py
  cubids/data/schema.json
  cubids/tests/test_apply.py
  cubids/utils.py
  cubids/workflows.py
  docs/api.rst
Labels: enhancement

#430 Pass schema along to workflows
  cubids/validator.py
  cubids/workflows.py
Labels: bug

#435 Clarify handling of non-BIDS entities in entity sets (e.g., `fmap-epi`)
  cubids/utils.py
  docs/example.rst
Labels: documentation, testing

#432 Use cluster number in non-dominant acquisition variant names
  cubids/tests/data/BIDS_Dataset/sub-03/ses-phdiff/func/sub-03_ses-phdiff_task-rest_bold.json
  cubids/tests/data/BIDS_Dataset/sub-04/ses-phdiff/func/sub-04_ses-phdiff_task-rest_bold.json
  cubids/tests/data/inconsistent/sub-03/ses-phdiff/func/sub-03_ses-phdiff_task-rest_bold.json
  cubids/tests/test_bond.py
  cubids/tests/test_variants.py
  cubids/utils.py
  docs/_static/v0_edited_summary.csv
  docs/_static/v0_summary.csv
  docs/example.rst
  docs/glossary.rst
  docs/usage.rst
Labels: enhancement

#431 Improve testing of command-line interfaces
  .circleci/config.yml
  cubids/cli.py
  cubids/tests/test_cli.py
  cubids/workflows.py
Labels: testing

#438 Add "C" prefix to cluster values in variants
  cubids/tests/test_variants.py
  cubids/utils.py
Labels: enhancement

#443 Remove non-alphanumeric characters from variant values
  cubids/utils.py
Labels: bug

#442 Bookend entity sets with datatype and acquisition entities
  cubids/tests/data/CuBIDS_Toy_Dataset_Curation/v0_AcqGroupInfo.txt
  cubids/tests/data/CuBIDS_Toy_Dataset_Curation/v0_files.csv
  cubids/tests/data/CuBIDS_Toy_Dataset_Curation/v0_summary.csv
  cubids/tests/data/CuBIDS_Toy_Dataset_Curation/v1_AcqGroupInfo.txt
  cubids/tests/data/CuBIDS_Toy_Dataset_Curation/v1_files.csv
  cubids/tests/data/CuBIDS_Toy_Dataset_Curation/v1_summary.csv
  cubids/tests/data/CuBIDS_Toy_Dataset_Curation/v2_AcqGroupInfo.txt
  cubids/tests/data/CuBIDS_Toy_Dataset_Curation/v2_files.csv
  cubids/tests/data/CuBIDS_Toy_Dataset_Curation/v2_summary.csv
  cubids/tests/test_apply.py
  cubids/tests/test_bond.py
  cubids/tests/test_variants.py
  cubids/utils.py
  docs/_static/PNC_example_edited.csv
  docs/_static/PNC_post_apply_summary.csv
  docs/_static/PNC_pre_apply_summary_dwi_run1.csv
  docs/_static/PNC_pre_apply_summary_dwi_run1_deletion.csv
  docs/_static/v0_edited_summary.csv
  docs/_static/v0_summary.csv
  docs/about.rst
  docs/example.rst
  docs/glossary.rst
Labels: enhancement
