Repository PennLINC/CuBIDS, pull requests merged in 2025-01, with the labels that each got.

#372 Uniformize CLI named arguments to dash-only syntax
  cubids/cli.py
  cubids/workflows.py
Labels: breaking-change

#369 Switch from using pkg_resources to importlib.resources
  cubids/config.py
  cubids/tests/utils.py
Labels: maintenance

#367 Support BIDS URIs in CuBIDS apply
  cubids/cubids.py
  cubids/tests/test_apply.py
  cubids/workflows.py
  pyproject.toml
Labels: bug

#349 Test CLI utils
  cubids/cli.py
  cubids/tests/test_cli.py
  cubids/tests/utils.py
Labels: testing

#377 Fill in docstrings for functions in config.py and tests/utils.py
  cubids/config.py
  cubids/tests/utils.py
Labels: documentation

#366 Cleanup notebooks
  docs/notebooks/Fieldmaps.ipynb
  docs/notebooks/FirstProofofConcept.ipynb
  docs/notebooks/HTML_param_groups.ipynb
  docs/notebooks/JSON_PoC_read_write.ipynb
  docs/notebooks/Key_and_Param_Groups.ipynb
  docs/notebooks/PofC_Key_Values2.ipynb
  docs/notebooks/Tests/datatype-anat_reconstruction-refaced_suffix-T1w.csv
  docs/notebooks/Tests/datatype-func_run-1_suffix-bold_task-rest.csv
  docs/notebooks/Tests/datatype-func_run-2_suffix-bold_task-rest.csv
  docs/notebooks/keyparamgrouptest.ipynb
  docs/notebooks/metadata_image_param.ipynb
  docs/notebooks/rename_files_work.ipynb
  docs/notebooks/workwithtestdata.ipynb
Labels: documentation

#380 Provide option to run locally installed bids-validator
  cubids/cli.py
  cubids/validator.py
  cubids/workflows.py
Labels: enhancement

#382 Stop adding leading zero to run entity when renaming files
  cubids/cubids.py
  cubids/tests/test_apply.py
  cubids/tests/test_cubids.py
Labels: bug

#396 Use force_unlock in copy_exemplars Python workflow
  cubids/workflows.py
Labels: bug

#398 Add module docstrings for __about__.py, __init__.py, constants.py, and utils.py
  cubids/__about__.py
  cubids/__init__.py
  cubids/constants.py
  cubids/utils.py
Labels: documentation

#391 Add docstrings for cubids/cli.py
  cubids/cli.py
Labels: documentation

#397 Update docstrings for files in cubids/tests
  cubids/tests/test_apply.py
  cubids/tests/test_bond.py
  cubids/tests/test_cli.py
  cubids/tests/test_cubids.py
Labels: documentation, testing

#393 Block autocompletion of arguments in CLI
  cubids/cli.py
Labels: bug

#402 Avoid copying shell prompt $ when copying example commands from docs
  .gitignore
  docs/conf.py
Labels: documentation

#404 Fixing bug to allow filenames in cubids apply and cubids copy-exemplars
  cubids/cli.py
Labels: bug

#401 Updated docs explaining the installation for internetless use cases
  docs/conf.py
  docs/example.rst
  docs/installation.rst
  pyproject.toml
Labels: documentation

#409 cubids print-metadata-fields exits if no dataset_desciption.json
  cubids/workflows.py
Labels: bug

#406 Fix: Update CuBIDS to allow both longitudinal and cross-sectional structure by adding is_longitudinal attribute to CUBIDS class
  cubids/config.py
  cubids/cubids.py
  cubids/metadata_merge.py
  cubids/tests/test_apply.py
  cubids/tests/test_bond.py
  docs/conf.py
Labels: bug

#388 Add FAQ page
  .gitignore
  cubids/data/references.bib
  cubids/metadata_merge.py
  docs/api.rst
  docs/conf.py
  docs/contributing.rst
  docs/faq.rst
  docs/index.rst
  docs/usage.rst
Labels: documentation

#361 Make Tien the development lead and add code sprint participants to contributor list
  AUTHORS.rst
  CITATION.cff
Labels: maintenance

#416 Switch from conda to mamba in CircleCI tests
  .circleci/config.yml
Labels: testing, maintenance

#411 Add/edit cubids.py docstrings
  cubids/cubids.py
Labels: documentation

#394 Remove `--container` argument from CLIs
  cubids/__init__.py
  cubids/cli.py
  cubids/config.py
  cubids/tests/test_apply.py
  cubids/tests/test_bond.py
  cubids/tests/utils.py
  cubids/utils.py
  cubids/workflows.py
  pyproject.toml
Labels: breaking-change

#417 Variant renaming suggestions are ignoring tolerances
  cubids/config.py
  cubids/cubids.py
Labels: bug
